"""Original-state contracts from nine user-labeled gameplay recordings.

No game engine, action execution, simulated season, fitting or opponent cloning.
Histories always advance to the next ORIGINAL observation, never to a state
generated by the candidate. These tests cannot measure candidate season returns.
"""

import copy
import gzip
import json
import runpy
import signal
import time
from collections import Counter

import pytest

from scripts.check_fresh_cycle1 import check_action, read_histories, timeout_handler
from scripts.make_fresh_cycle1 import SOURCE
from scripts.tiered_gameplays import (
    FIXTURE,
    GROUPS,
    MANIFEST,
    ROOT,
    canonical,
    digest,
    read_game,
    save_once,
)

_, RECORDS = read_histories(FIXTURE)
CATALOG = json.loads(MANIFEST.read_text())
CASES = RECORDS["cases"]
FINAL = [c for c in CASES if "final-action" in c["conditions"]]
CREWS = [c for c in CASES if "peak-crew" in c["conditions"]]


@pytest.fixture(scope="module")
def module():
    return runpy.run_path(str(SOURCE))


@pytest.fixture
def policy(module):
    module["agent"].__globals__["_MEMORY"].clear()
    return module


def configuration(case):
    return RECORDS["configuration_by_episode"][str(case["episode"])]


def invoke(policy, obs, cfg):
    before = copy.deepcopy(obs)
    old_handler = signal.signal(signal.SIGALRM, timeout_handler)
    try:
        signal.setitimer(signal.ITIMER_REAL, 1.0)
        started = time.perf_counter()
        action = policy["agent"](obs, cfg)
        elapsed = time.perf_counter() - started
    finally:
        signal.setitimer(signal.ITIMER_REAL, 0)
        signal.signal(signal.SIGALRM, old_handler)
    assert elapsed < 1.0
    assert obs == before, "Candidate changed an original observation"
    check_action(obs, cfg, action)
    memory = policy["agent"].__globals__["_MEMORY"]
    targets = [tuple(target[0]) for target in memory.get("targets", {}).values()]
    assert len(targets) == len(set(targets)), "Two workers reserve the same productive visit"
    assert memory["token"] == (obs["player"], obs["day"], 10, cfg["episodeSteps"] - 2)
    return action


@pytest.mark.parametrize("game", CATALOG["games"], ids=lambda g: f"{g['tier']}-{g['episode']}")
def test_lossless_archive_and_selected_observations_match_original_recording(game):
    compressed = (ROOT / game["archive_path"]).read_bytes()
    assert digest(compressed) == game["archive_sha256"]
    raw = gzip.decompress(compressed)
    assert len(raw) == game["raw_bytes"] and digest(raw) == game["raw_sha256"]
    original = read_game(raw, game["episode"])
    assert game["episode"] in GROUPS[game["tier"]]
    for seat, state in enumerate(original["steps"][-1]):
        assert state["status"] == "DONE"
        assert state["reward"] == state["observation"]["farms"][seat]["money"]
    for case in CASES:
        if case["episode"] == game["episode"]:
            obs = original["steps"][case["state_index"]][case["seat"]]["observation"]
            assert case["observation"] == obs
            assert digest(canonical(obs)) == case["observation_sha256"]
            assert case["source_sha256"] == game["raw_sha256"]
    for history in RECORDS["histories"]:
        if history["episode"] == game["episode"]:
            for index, obs in zip(history["state_indices"], history["observations"], strict=True):
                assert obs == original["steps"][index][history["seat"]]["observation"]
    assert RECORDS["configuration_by_episode"][str(game["episode"])] == original["configuration"]


@pytest.mark.parametrize("case", CASES, ids=lambda c: c["id"] + "-" + "_".join(c["conditions"]))
def test_recorded_economic_condition_has_feasible_nonmutating_decision(policy, case):
    obs, cfg = case["observation"], configuration(case)
    assert obs["player"] == case["seat"]
    assert obs["day"] * cfg["turnsPerDay"] + obs["hour"] == case["state_index"] <= 718
    # Independent server-observed price vector, not policy-produced expected quotes.
    planner = policy["Planner"](obs, cfg)
    assert planner.prices == obs["market"]["prices"]
    farm, private = obs["farms"][case["seat"]], obs["private"]
    conditions = case["conditions"]
    if "peak-crew" in conditions:
        assert len(farm["hands"]) >= 11
    if "peak-storage" in conditions:
        assert (
            sum(private["shed"].values()) + sum(sum(inv.values()) for inv in private["inventories"])
            > 100
        )
    if "price-floor" in conditions:
        assert 1 in obs["market"]["prices"].values()
    if "duplicate-demand" in conditions:
        assert max(Counter(obs["town"]["unlocked_shops"]).values()) >= 2
    if "late-feed-risk" in conditions:
        assert obs["hour"] >= 20 and obs["day"] < 29
        assert any(
            t.get("animal") and t["consecutive_unfed"] >= 1 and not t["fed_today"]
            for row in farm["tiles"]
            for t in row
            if isinstance(t, dict)
        )
    if "decay-pressure" in conditions:
        assert any(
            t.get("crop")
            and t["yield_units"] > 0
            and 0 <= t["max_lifespan_step"] <= case["state_index"] + 4
            for row in farm["tiles"]
            for t in row
            if isinstance(t, dict)
        )
    action = invoke(policy, obs, cfg)
    if obs["day"] == 29:
        assert not any(o[0].startswith("BUY") for o in action["market"])


@pytest.mark.parametrize("case", FINAL, ids=lambda c: c["id"])
def test_recorded_final_turn_sells_all_deposited_products_and_reserves_no_feed(policy, case):
    obs, cfg = case["observation"], configuration(case)
    action = invoke(policy, obs, cfg)
    products = set(obs["market"]["prices"])
    stock = Counter(obs["private"]["shed"])
    for i, command in enumerate([action["farmer"], *action["hands"]]):
        if command[0] == "DROP":
            for item, quantity in obs["private"]["inventories"][i].items():
                stock[item] += min(quantity, max(0, cfg["shedCapacity"] - sum(stock.values())))
        elif command[0] == "PLACE" and command[1] in products:
            stock[command[1]] += command[2]
    assert all(order[0] == "SELL" for order in action["market"])
    sales = Counter()
    for _, item, quantity in action["market"]:
        sales[item] += quantity
    assert sales == Counter({p: n for p, n in stock.items() if p in products})
    # This proves liquidation quantities, not an optimal deposit or a realized fill price.


@pytest.mark.parametrize(
    "episode,product,expected",
    [
        (108377045, "STRAWBERRY", 37),
        (108377042, "WOOL", 25),
        (108359085, "CARROT", 25),
        (108380097, "WOOL", 49),
        (108375914, "STRAWBERRY", 25),
        (108371392, "WOOL", 37),
        (108378358, "MILK", 25),
        (108365679, "WHEAT", 43),
        (108364290, "CARROT", 37),
    ],
)
def test_recorded_town_composition_has_hand_calculated_demand(policy, episode, product, expected):
    case = next(c for c in FINAL if c["episode"] == episode and c["seat"] == 0)
    p = policy["Planner"](case["observation"], configuration(case))
    assert p.demand[product] == expected
    assert p.demand["FERTILIZER"] == 0
    assert len(case["observation"]["town"]["unlocked_shops"]) == 8


@pytest.mark.parametrize("case", CREWS, ids=lambda c: c["id"])
def test_seat_relabeling_preserves_our_plan_on_recorded_large_farms(policy, case):
    obs, cfg = case["observation"], configuration(case)
    original = invoke(policy, obs, cfg)
    mirrored = copy.deepcopy(obs)
    mirrored["player"] = 1 - obs["player"]
    mirrored["farms"].reverse()
    # Derived metamorphic case: our same private state stays ours, no rival private data.
    policy["agent"].__globals__["_MEMORY"].clear()
    assert invoke(policy, mirrored, cfg) == original


@pytest.mark.parametrize("history", RECORDS["histories"], ids=lambda h: h["id"])
def test_short_original_history_handles_dawn_reset_and_terminal_delivery(policy, history):
    cfg = configuration(history)
    assert len(history["observations"]) == 4
    assert history["state_indices"] == list(
        range(history["state_indices"][0], history["state_indices"][0] + 4)
    )
    memory = policy["agent"].__globals__["_MEMORY"]
    modes = {}
    for mode in ("warm", "warm-repeat", "cold"):
        memory.clear()
        actions = []
        for obs in history["observations"]:
            if mode == "cold":
                memory.clear()
            actions.append(invoke(policy, obs, cfg))
        modes[mode] = actions
    assert modes["warm"] == modes["warm-repeat"]
    if history["kind"] == "dawn-rehire":
        before, after = history["observations"][:2]
        assert before["hour"] == 23 and after["hour"] == 0
        assert after["day"] == before["day"] + 1
        assert after["farms"][after["player"]]["hands"] == []
    else:
        assert history["state_indices"] == [715, 716, 717, 718]


def test_tier_fixture_has_both_seats_and_does_not_invent_missing_events():
    assert len(CASES) == 136 and len(RECORDS["histories"]) == 36
    assert len({(c["episode"], c["seat"], c["state_index"]) for c in CASES}) == len(CASES)
    for tier, episodes in GROUPS.items():
        for episode in episodes:
            assert {c["seat"] for c in CASES if c["episode"] == episode and c["tier"] == tier} == {
                0,
                1,
            }
    no_floor_game = [c for c in CASES if c["episode"] == 108377042]
    assert all("price-floor" not in c["conditions"] for c in no_floor_game)
    assert all(
        "action" not in c["observation"] and "rewards" not in c["observation"] for c in CASES
    )


def test_archive_writer_refuses_to_replace_different_prior_bytes(tmp_path):
    target = tmp_path / "recording.json"
    save_once(target, b"original data")
    save_once(target, b"original data")
    with pytest.raises(FileExistsError):
        save_once(target, b"different data")
    assert target.read_bytes() == b"original data"
